//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDrinkzy.ServiceIngredients {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ingredients", Namespace="http://schemas.datacontract.org/2004/07/Modellayer")]
    [System.SerializableAttribute()]
    public partial class Ingredients : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProcentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Procent {
            get {
                return this.ProcentField;
            }
            set {
                if ((this.ProcentField.Equals(value) != true)) {
                    this.ProcentField = value;
                    this.RaisePropertyChanged("Procent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceIngredients.IServiceIngredients")]
    public interface IServiceIngredients {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/GetIngredients", ReplyAction="http://tempuri.org/IServiceIngredients/GetIngredientsResponse")]
        WpfDrinkzy.ServiceIngredients.Ingredients[] GetIngredients(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/GetIngredients", ReplyAction="http://tempuri.org/IServiceIngredients/GetIngredientsResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.ServiceIngredients.Ingredients[]> GetIngredientsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/GetIngredientsList", ReplyAction="http://tempuri.org/IServiceIngredients/GetIngredientsListResponse")]
        WpfDrinkzy.ServiceIngredients.Ingredients[] GetIngredientsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/GetIngredientsList", ReplyAction="http://tempuri.org/IServiceIngredients/GetIngredientsListResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.ServiceIngredients.Ingredients[]> GetIngredientsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/CreateIngredients", ReplyAction="http://tempuri.org/IServiceIngredients/CreateIngredientsResponse")]
        void CreateIngredients(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/CreateIngredients", ReplyAction="http://tempuri.org/IServiceIngredients/CreateIngredientsResponse")]
        System.Threading.Tasks.Task CreateIngredientsAsync(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/DeleteIngredients", ReplyAction="http://tempuri.org/IServiceIngredients/DeleteIngredientsResponse")]
        void DeleteIngredients(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIngredients/DeleteIngredients", ReplyAction="http://tempuri.org/IServiceIngredients/DeleteIngredientsResponse")]
        System.Threading.Tasks.Task DeleteIngredientsAsync(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceIngredientsChannel : WpfDrinkzy.ServiceIngredients.IServiceIngredients, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceIngredientsClient : System.ServiceModel.ClientBase<WpfDrinkzy.ServiceIngredients.IServiceIngredients>, WpfDrinkzy.ServiceIngredients.IServiceIngredients {
        
        public ServiceIngredientsClient() {
        }
        
        public ServiceIngredientsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceIngredientsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIngredientsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIngredientsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfDrinkzy.ServiceIngredients.Ingredients[] GetIngredients(string name) {
            return base.Channel.GetIngredients(name);
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.ServiceIngredients.Ingredients[]> GetIngredientsAsync(string name) {
            return base.Channel.GetIngredientsAsync(name);
        }
        
        public WpfDrinkzy.ServiceIngredients.Ingredients[] GetIngredientsList() {
            return base.Channel.GetIngredientsList();
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.ServiceIngredients.Ingredients[]> GetIngredientsListAsync() {
            return base.Channel.GetIngredientsListAsync();
        }
        
        public void CreateIngredients(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients) {
            base.Channel.CreateIngredients(Ingredients);
        }
        
        public System.Threading.Tasks.Task CreateIngredientsAsync(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients) {
            return base.Channel.CreateIngredientsAsync(Ingredients);
        }
        
        public void DeleteIngredients(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients) {
            base.Channel.DeleteIngredients(Ingredients);
        }
        
        public System.Threading.Tasks.Task DeleteIngredientsAsync(WpfDrinkzy.ServiceIngredients.Ingredients Ingredients) {
            return base.Channel.DeleteIngredientsAsync(Ingredients);
        }
    }
}
